FROM alpine:edge
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN apk update \
    && apk add nginx \
    && mkdir -p /run/nginx
ADD ./index.html /www/   
CMD ["nginx", "-g", "daemon off;"]