FROM centos:7
ADD ./daemon.txt /
RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    && rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
RUN yum makecache \
    && yum -y install php72w-fpm php72w-cli php72w-devel php72w-pear
CMD ["tail", "-f", "daemon.txt"]